# Description: Defines a state machine for a scenario in which a robot patrols a certain area
# Author: Alex Mitrevski
# Email: aleksandar.mitrevski@h-brs.de
sm_id: mdr_demo_patrol
states: [GO_TO_START, WAIT_FOR_COMMAND, GO_TO_DOOR, DETECT_HANDLE, OPEN_DOOR, ASK_TO_OPEN_DOOR, PUSH_DOOR_OPEN,
         GO_TO_DOOR_CENTER, GO_THROUGH_DOOR, GO_BACK_TO_DOOR_CENTER, CLOSE_DOOR]
outcomes: [DONE, TIMEOUT, FAILED]
state_descriptions:
    - state:
        name: GO_TO_START
        #state_module_name: mdr_navigation_behaviours.move_base
        #state_class_name: MoveBase
        state_module_name: mdr_sciroc_door_open.scenario_states.wait_for_command
        state_class_name: SimulatedGoTo
        transitions:
            - transition:
                name: succeeded
                state: WAIT_FOR_COMMAND
            - transition:
                name: failed
                state: GO_TO_START
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: destination_locations
                value: [START_DOOR]
            - argument:
                name: number_of_retries
                value: 1

    - state:
        name: WAIT_FOR_COMMAND
        state_module_name: mdr_sciroc_door_open.scenario_states.wait_for_command
        state_class_name: WaitForCommand
        transitions:
            - transition:
                name: succeeded
                state: GO_TO_DOOR
            - transition:
                name: failed
                state: WAIT_FOR_COMMAND
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 1

    - state:
        name: GO_TO_DOOR
        #state_module_name: mdr_navigation_behaviours.move_base
        #state_class_name: MoveBase
        state_module_name: mdr_sciroc_door_open.scenario_states.wait_for_command
        state_class_name: SimulatedGoTo
        transitions:
            - transition:
                name: succeeded
                state: DETECT_HANDLE
            - transition:
                name: failed
                state: GO_TO_DOOR
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: destination_locations
                # alternatively DOOR_CENTER
                value: [DOOR_HANDLE]
            - argument:
                name: number_of_retries
                value: 1

    - state:
        name: DETECT_HANDLE
        state_module_name: mdr_sciroc_door_open.scenario_states.detect_handle
        state_class_name: DetectHandle
        transitions:
            - transition:
                name: succeeded
                state: OPEN_DOOR
            - transition:
                name: failed
                state: GO_TO_DOOR
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 2

    - state:
        name: OPEN_DOOR
        state_module_name: mdr_sciroc_door_open.scenario_states.open_door
        state_class_name: OpenDoor
        transitions:
            - transition:
                name: succeeded
                state: GO_THROUGH_DOOR
            - transition:
                name: failed
                state: OPEN_DOOR
            - transition:
                name: failed_after_retrying
                state: ASK_TO_OPEN_DOOR
        arguments:
            - argument:
                name: number_of_retries
                value: 1
            - argument:
                name: gripper_package
                value: mas_hsr_gripper_controller

    - state:
        name: ASK_TO_OPEN_DOOR
        state_module_name: mdr_sciroc_door_open.scenario_states.open_door
        state_class_name: AskToOpenDoor
        transitions:
            - transition:
                name: succeeded
                state: GO_TO_DOOR_CENTER

    - state:
        name: GO_TO_DOOR_CENTER
        #state_module_name: mdr_navigation_behaviours.move_base
        #state_class_name: MoveBase
        state_module_name: mdr_sciroc_door_open.scenario_states.wait_for_command
        state_class_name: SimulatedGoTo
        transitions:
            - transition:
                name: succeeded
                state: PUSH_DOOR_OPEN
            - transition:
                name: failed
                state: GO_TO_DOOR_CENTER
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: destination_locations
                value: [DOOR_CENTER]
            - argument:
                name: number_of_retries
                value: 1

    - state:
        name: PUSH_DOOR_OPEN
        state_module_name: mdr_sciroc_door_open.scenario_states.open_door
        state_class_name: PushDoorOpen
        transitions:
            - transition:
                name: succeeded
                state: GO_BACK_TO_DOOR_CENTER
            - transition:
                name: failed
                state: PUSH_DOOR_OPEN
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 1
            - argument:
                name: movement_duration
                value: 10
            - argument:
                name: movement_speed
                value: 0.1

    - state:
        name: GO_BACK_TO_DOOR_CENTER
        #state_module_name: mdr_navigation_behaviours.move_base
        #state_class_name: MoveBase
        state_module_name: mdr_sciroc_door_open.scenario_states.wait_for_command
        state_class_name: SimulatedGoTo
        transitions:
            - transition:
                name: succeeded
                state: GO_THROUGH_DOOR
            - transition:
                name: failed
                state: GO_BACK_TO_DOOR_CENTER
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: destination_locations
                value: [DOOR_CENTER]
            - argument:
                name: number_of_retries
                value: 1

    - state:
        name: GO_THROUGH_DOOR
        #state_module_name: mdr_navigation_behaviours.move_base
        #state_class_name: MoveBase
        state_module_name: mdr_sciroc_door_open.scenario_states.wait_for_command
        state_class_name: SimulatedGoTo
        transitions:
            - transition:
                name: succeeded
                state: CLOSE_DOOR
            - transition:
                name: failed
                state: GO_THROUGH_DOOR
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: destination_locations
                value: [OTHER_SIDE_OF_DOOR]
            - argument:
                name: number_of_retries
                value: 1

    - state:
        name: CLOSE_DOOR
        state_module_name: mdr_sciroc_door_open.scenario_states.close_door
        state_class_name: CloseDoor
        transitions:
            - transition:
                name: succeeded
                state: DONE
            - transition:
                name: failed
                state: CLOSE_DOOR
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 1
            - argument:
                name: movement_duration
                value: 5
            - argument:
                name: movement_speed
                value: 0.1
