# Description: Defines a state machine for a simple pick scenario (picking an object from a surface)
# Author: Alex Mitrevski
# Email: aleksandar.mitrevski@h-brs.de
sm_id: mdr_demo_simple_pick
states: [PERCEIVE_TABLE, PICK_OBJECT, FIND_OBJECTS_BEFORE_PICKING, WAIT_FOR_CONTINUE_CONFIRMATION]
outcomes: [DONE, FAILED]
state_descriptions:
    - state:
        name: PERCEIVE_TABLE
        state_module_name: mdr_perception_behaviours.perceive_planes
        state_class_name: PerceivePlanes
        transitions:
            - transition:
                name: succeeded
                state: PICK_OBJECT
            - transition:
                name: failed
                state: PERCEIVE_TABLE
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 10
            - argument:
                name: plane_prefix
                value: table
    - state:
        name: PICK_OBJECT
        state_module_name: mdr_manipulation_behaviours.pick_closest_from_surface
        state_class_name: PickClosestFromSurface
        transitions:
            - transition:
                name: succeeded
                state: WAIT_FOR_CONTINUE_CONFIRMATION
            - transition:
                name: failed
                state: PICK_OBJECT
            - transition:
                name: failed_after_retrying
                state: FAILED
            - transition:
                name: find_objects_before_picking
                state: FIND_OBJECTS_BEFORE_PICKING
        arguments:
            - argument:
                name: number_of_retries
                value: 3
            - argument:
                name: picking_surface_prefix
                value: table
    - state:
        name: FIND_OBJECTS_BEFORE_PICKING
        state_module_name: mdr_perception_behaviours.perceive_planes
        state_class_name: PerceivePlanes
        transitions:
            - transition:
                name: succeeded
                state: PICK_OBJECT
            - transition:
                name: failed
                state: FIND_OBJECTS_BEFORE_PICKING
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 10
            - argument:
                name: plane_prefix
                value: table
    - state:
        name: WAIT_FOR_CONTINUE_CONFIRMATION
        state_module_name: mdr_hri_behaviours.wait_for_continue_confirmation
        state_class_name: WaitForContinueConfirmation
        transitions:
            - transition:
                name: continue
                state: PERCEIVE_TABLE
            - transition:
                name: stop
                state: DONE
        arguments:
            - argument:
                name: timeout
                value: 120.0
