# Description: Defines a state machine for a simple pick scenario (picking an object from a surface)
# Author: Alex Mitrevski
# Email: aleksandar.mitrevski@h-brs.de
sm_id: mdr_demo_simple_pick
states: [GO_TO_TABLE, PERCEIVE_TABLE, PLACE_OBJECT, WAIT_FOR_CONTINUE_CONFIRMATION]
outcomes: [DONE, FAILED]
state_descriptions:
    - state:
        name: GO_TO_TABLE
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: PERCEIVE_TABLE
            - transition:
                name: failed
                state: GO_TO_TABLE
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: destination_locations
                value: [table]
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: PERCEIVE_TABLE
        state_module_name: mdr_perception_behaviours.perceive_planes
        state_class_name: PerceivePlanes
        transitions:
            - transition:
                name: succeeded
                state: PLACE_OBJECT
            - transition:
                name: failed
                state: PERCEIVE_TABLE
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
            - argument:
                name: plane_prefix
                value: table
    - state:
        name: PLACE_OBJECT
        state_module_name: mdr_manipulation_behaviours.place
        state_class_name: Place
        transitions:
            - transition:
                name: succeeded
                state: WAIT_FOR_CONTINUE_CONFIRMATION
            - transition:
                name: failed
                state: PLACE_OBJECT
            - transition:
                name: failed_after_retrying
                state: FAILED
        arguments:
            - argument:
                name: number_of_retries
                value: 3
            - argument:
                name: placing_surface_prefix
                value: table
    - state:
        name: WAIT_FOR_CONTINUE_CONFIRMATION
        state_module_name: mdr_hri_behaviours.wait_for_continue_confirmation
        state_class_name: WaitForContinueConfirmation
        transitions:
            - transition:
                name: continue
                state: GO_TO_TABLE
            - transition:
                name: stop
                state: DONE
        arguments:
            - argument:
                name: timeout
                value: 120.0
